Errors when running lj_liquid_structurefactor.py with v4.2.2
The arguments of `system.analysis.structure_factor()` needed to be named to run the script without error message otherwise the error was:

```shell
pypresso samples/lj_liquid_structurefactor.py

=======================================================
=              lj_liquid_structurefactor.py           =
=======================================================

Traceback (most recent call last):
  File "/home/szitz/espresso-v422/samples/lj_liquid_structurefactor.py", line 80, in <module>
    structurefactor_bins = len(system.analysis.structure_factor())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "script_interface.pyx", line 476, in espressomd.script_interface.ScriptInterfaceHelper.generate_caller.template_method
  File "script_interface.pyx", line 172, in espressomd.script_interface.PScriptInterface.call_method
RuntimeError: Parameter 'sf_order' is missing.
```